// <auto-generated />
using CodeFistNET4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFistNET4.Migrations
{
    [DbContext(typeof(SKMDbContext))]
    [Migration("20251113060308_3th")]
    partial class _3th
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiKHID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAccount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiKHID");

                    b.HasIndex("idAccount")
                        .IsUnique();

                    b.ToTable("KhachHang", "QLKH");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.LoaiKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiKH", "QLKH");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.LoaiKhuyenMai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiKhuyenMais");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.MaKhuyenMai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("lkmID")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("percentage")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("lkmID");

                    b.ToTable("maKhuyenMais");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.KhachHang", b =>
                {
                    b.HasOne("CodeFistNET4.Models.DataModels.LoaiKhachHang", "LoaiKhachHang")
                        .WithMany()
                        .HasForeignKey("LoaiKHID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFistNET4.Models.DataModels.Account", "Account")
                        .WithOne("khachHang")
                        .HasForeignKey("CodeFistNET4.Models.DataModels.KhachHang", "idAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("LoaiKhachHang");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.MaKhuyenMai", b =>
                {
                    b.HasOne("CodeFistNET4.Models.DataModels.LoaiKhuyenMai", "LoaiKhuyenMai")
                        .WithMany()
                        .HasForeignKey("lkmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhuyenMai");
                });

            modelBuilder.Entity("CodeFistNET4.Models.DataModels.Account", b =>
                {
                    b.Navigation("khachHang")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
